### ISSUE TITLE
fix test warnings in bitcoin and ethereum

### ISSUE THREAD

**Issue by shuimuliang** [cregis-web3/anychain#11]
`cargo test --all-features`

warning: unused import: `SecretKey`
 --> ethereum/src/address.rs:4:26
  |
4 |     libsecp256k1::{self, SecretKey},
  |                          ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `chainlib_core::libsecp256k1`
  --> bitcoin/src/transaction.rs:18:5
   |
18 | use chainlib_core::libsecp256k1;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `core::str::FromStr`
  --> bitcoin/src/lib.rs:26:9
   |
26 |     use core::str::FromStr;
   |         ^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::transaction::*`
  --> bitcoin/src/lib.rs:28:9
   |
28 |     use crate::transaction::*;
   |         ^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `crate::address::*`
  --> bitcoin/src/lib.rs:29:9
   |
29 |     use crate::address::*;
   |         ^^^^^^^^^^^^^^^^^

warning: unused import: `crate::amount::*`
  --> bitcoin/src/lib.rs:30:9
   |
30 |     use crate::amount::*;
   |         ^^^^^^^^^^^^^^^^

warning: unused import: `super::*`
  --> bitcoin/src/lib.rs:31:9
   |
31 |     use super::*;
   |         ^^^^^^^^

warning: unused import: `rand::thread_rng`
  --> bitcoin/src/lib.rs:32:9
   |
32 |     use rand::thread_rng;
   |         ^^^^^^^^^^^^^^^^

warning: use of deprecated field `ethabi::Function::constant`: The constant attribute was removed in Solidity 0.5.0 and has been replaced with stateMutability.
  --> ethereum/src/transaction.rs:53:9
   |
53 |         constant: None,
   |         ^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: unused import: `sha2::digest::typenum::Bit`
  --> bitcoin/src/transaction.rs:16:5
   |
16 | use sha2::digest::typenum::Bit;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused variable: `hrp`
   --> bitcoin/src/address.rs:184:22
    |
184 |                 let (hrp, data, variant) = bech32::decode(&address)?;
    |                      ^^^ help: if this is intentional, prefix it with an underscore: `_hrp`
    |
    = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `variant`
   --> bitcoin/src/address.rs:184:33
    |
184 |                 let (hrp, data, variant) = bech32::decode(&address)?;
    |                                 ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_variant`

warning: unused variable: `hrp`
   --> bitcoin/src/transaction.rs:135:18
    |
135 |             let (hrp, data, variant) = bech32::decode(&address.to_string())?;
    |                  ^^^ help: if this is intentional, prefix it with an underscore: `_hrp`

warning: unused variable: `variant`
   --> bitcoin/src/transaction.rs:135:29
    |
135 |             let (hrp, data, variant) = bech32::decode(&address.to_string())?;
    |                             ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_variant`

warning: unused variable: `signature`
   --> bitcoin/src/transaction.rs:732:24
    |
732 |     fn sign(&mut self, signature: Vec<u8>, recid: u8) -> Result<Vec<u8>, TransactionError> {
    |                        ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_signature`

warning: unused variable: `recid`
   --> bitcoin/src/transaction.rs:732:44
    |
732 |     fn sign(&mut self, signature: Vec<u8>, recid: u8) -> Result<Vec<u8>, TransactionError> {
    |                                            ^^^^^ help: if this is intentional, prefix it with an underscore: `_recid`

warning: variable does not need to be mutable
   --> bitcoin/src/transaction.rs:880:9
    |
880 |         mut public_key: Vec<u8>,
    |         ----^^^^^^^^^^
    |         |
    |         help: remove this `mut`
    |
    = note: `#[warn(unused_mut)]` on by default

warning: type alias `N` is never used
  --> bitcoin/src/lib.rs:33:10
   |
33 |     type N = super::network::Testnet;
   |          ^
   |
note: the lint level is defined here
  --> bitcoin/src/lib.rs:2:31
   |
2  | #![warn(unused_extern_crates, dead_code)]
   |                               ^^^^^^^^^

warning: constant `ACOUNTS` is never used
  --> bitcoin/src/lib.rs:39:11
   |
39 |     const ACOUNTS: [(&str,&str);2] = [
   |           ^^^^^^^

   Compiling anychain v0.0.1 (/Users/cairo/anychain/anychain)
warning: `bitcoin` (lib) generated 17 warnings
warning: `ethereum` (lib) generated 2 warnings

**Comment by aya015757881** [comment]
merged into issue #12
